# -*- coding: utf-8 -*-
# Aktivitäten: Etappe;Name;Adresse;Ort;Bewertung;Reviews;Kategorie;Preis;Dauer;Wege;Mindestalter;Warum;BesteZeit;Buchung;Website;Lat;Lng;Hinweis
A = []
def a(*x): A.append(x)

E1="1 | Kapstadt (4.-8. Okt)"
a(E1,"Boulders Beach Pinguine","Kleintuin Road, Boulders","Simon's Town 7995","4.4","8660","Tiere","R245 Erw. / R120 Kind 2-11 / unter 2 gratis","45-75 Min","Ja - Holz-Boardwalk","keines","Pinguine watscheln neben dem Steg; der Badestrand daneben ist eine flache, wellenarme Bucht zwischen Granitblöcken","08:00-09:30, dann weiter","Nein","https://www.sanparks.org/parks/table-mountain/rates-entry-fees","-34.1970","18.4510","Kein Schatten auf dem Boardwalk - Hut zwingend. Pinguine beissen, Abstand halten")
a(E1,"Two Oceans Aquarium","Dock Road, V&A Waterfront","Cape Town 8002","4.2","5410","Regenwetter / Tiere","R280 Erw. / R130 Kind 4-13 / unter 4 gratis","1.5-2 Std","Ja - komplett stufenlos, Lift","keines","Der Schlechtwetter- und Wind-Joker: drinnen, warm, Bänke vor den grossen Scheiben, Touch Pool knietief und beaufsichtigt","09:30 zur Öffnung, dann ist es leer","Online empfohlen","https://www.aquarium.co.za/visit-us/plan-your-trip","-33.9077","18.4173","Toiletten mit Wickeltisch")
a(E1,"Kirstenbosch + Boomslang","Rhodes Drive, Gate 1","Newlands, Cape Town 7735","4.7","10184","Natur","ca. R270 Erw. / Kinder unter 6 gratis","1.5-2.5 Std","Teilweise - untere Wege ja, Boomslang-Rampe steil","keines","Riesige Picknickrasen, viel Baumschatten, Teiche und der Baumwipfelpfad; im Oktober Höhepunkt der Frühlingsblüte","09:00-11:00","Nein","https://www.sanbi.org/gardens/kirstenboch/visitor-information/information/","-33.9884","18.4325","Nur 20 Min. von Hout Bay über Constantia Nek - kürzester Ausflug der Woche")
a(E1,"Tafelberg-Seilbahn","Tafelberg Road, Lower Cable Station","Cape Town 8001","4.6","17613","Adventure / Natur","R475 Erw. / R230 Kind 4-17 / unter 4 gratis (online, retour)","1.5-2 Std","Oben bedingt - Dassie-Weg befestigt, Gondel voll","keines","Vier Minuten Auffahrt, oben flache Rundwege; das Erlebnis ist kurz genug fürs Kind","Erste Fahrt 08:00-08:30","Online, dringend","https://www.tablemountain.net/plan-your-visit/ticket-prices/","-33.9357","18.4033","Am Morgen Betriebsstatus prüfen - bei Wind geschlossen. Oben deutlich kälter, Jacke mitnehmen. Trage statt ")
a(E1,"Green Point Urban Park (Tot-Lot)","1 Fritz Sonnenberg Road","Green Point, Cape Town 8005","4.6","694","Spielplatz / Natur","Gratis","1-2 Std","Ja - durchgehend geteert","Tot-Lot ausdrücklich für 1-6 Jahre","Eigener Spielplatz für 1-6-Jährige mit Rutschen und Schaukeln, dazu Labyrinth und Biodiversity Garden","08:30-11:00 oder 15:30-18:00","Nein","https://www.capetownmagazine.com/green-point-park","-33.9060","18.4113","Park Café mit Kindermenü; taeglich 07:00-19:00")
a(E1,"Sea Point Pavilion Kinderbecken","Lower Beach Road","Sea Point, Cape Town 8005","4.4","4609","Wasser","R37.50 Erw. / R22 Kind","1-1.5 Std","Ja - ebenerdig","keines","Eigenes Kinderbecken 11,5 x 28 m und nur 40 cm tief, Rettungsschwimmer im Dienst - die sichere Alternative zum eiskalten Atlantik","11:00-13:00, wenn die Sonne das flache Becken gewärmt hat","Nein","https://www.capetown.travel/beat-the-summer-heat-at-these-cape-town-public-pools/","-33.9165","18.3855","Ungeheiztes Meerwasser - im Oktober kalt, kurze Planschzeit. MONTAGS erst ab 12:00")
a(E1,"Blue Train Park","Beach Road, beim Leuchtturm","Mouille Point, Cape Town 8005","4.2","1057","Spielplatz","R35 pro Person inkl. einer Zugfahrt / unter 1 Jahr gratis","1-1.5 Std","Ja","keines - Züge sind auf Kinder ausgelegt","Miniatur-Eisenbahn zum Mitfahren auf eingezäuntem Gelände - das Kind kann nicht auf die Strasse laufen","10:00-11:30 oder 15:30-17:30","Nein","https://thebluetrainpark.co.za/","-33.8988","18.4074","MONTAGS geschlossen (ausser Ferien) - für Mo 5.10. nicht einplanen")
a(E1,"St James & Dalebrook Gezeitenbecken","St James Beach, Main Road / Dalebrook Road","St James 7945","4.2","141","Wasser / Strand","Gratis","1.5-2 Std","Eingeschränkt - Bahnunterführung mit Treppe, dann Sand","keines","Ummauerte Gezeitenbecken sperren das offene Meer aus: keine Brandung, keine Strömung, teils nur knöcheltief. Die besten Wasserplätze für ein 4-jähriges Kind in Kapstadt","Zwei Stunden vor Niedrigwasser, 09:30-11:30","Nein","https://www.sa-venues.com/things-to-do/westerncape/dip-in-an-ocean-pool/","-34.1185","18.4595","Badeschuhe wegen Algen. Nicht bewacht - Eltern bleiben im Wasser. False Bay ist wärmer als der Atlantik")
a(E1,"Imhoff Farm + Higgeldy Piggeldy Farmyard","Kommetjie Road (M65)","Kommetjie / Ocean View 7975","4.4","3839","Tiere","Gelände gratis / Streichelzoo R20 p.P.","1.5-2.5 Std","Ja - überwiegend befestigt","keines für den Farmyard","Streichelgehege, Kamele und Ponys, flaches Farmgelände mit Rasen und mehreren Restaurants","Vormittags 09:30-12:00","Nein","https://www.imhofffarm.co.za","-34.1385","18.3620","ACHTUNG: Streichelzoo nur Mo-Fr 08:00-17:00, am Wochenende zu. Kamelreiten: Mindestalter vorab klären")
a(E1,"World of Birds & Monkey Park","Valley Road","Hout Bay, Cape Town 7806","4.4","5414","Tiere / Regenwetter","R145 Erw. / R60 Kind 3-18 / unter 3 gratis","1.5-2 Std","Ja - flache Wege, Leihwagen für Gepäck R20","keines","Eigener Kinder-Spielplatz mit Sandkasten, viele überdachte Gänge, Wickelmöglichkeit - und nur 10 Min. von eurer Unterkunft","Ankunft 11:00: Pinguinfütterung 11:30, Monkey Jungle 11:30-13:00","Nein","https://worldofbirds.co.za/plan-your-visit/","-34.0333","18.3592","Im Monkey Jungle Kind auf den Arm nehmen - Affen greifen nach Gegenständen. TripAdvisor nur 3.9 wegen Gehegegrössen")
a(E1,"Duiker Island Robbenfahrt (40 Min.)","Hout Bay Harbour, Harbour Road","Hout Bay, Cape Town 7806","4.3","222","Tiere / Adventure","R130 Erw. / R70 Kind unter 14 / bis 2 Jahre gratis","40 Min","Nein - Wagen bleibt am Hafen","kein formales, Rettungsweste in Kindergrösse vorab erfragen","Die kürzeste Tierbeobachtungstour der Region - 40 Minuten passen genau in eine Kinder-Aufmerksamkeitsspanne","Erste Abfahrt 09:00-10:00, dann ist die Bucht ruhig","Empfohlen","https://drumbeatcharters.co.za/40-minute-seal-colony-cruise/","-34.0503","18.3480","Keine Toilette an Bord. Bei Wind schaukelt es - dann lieber absagen. 8 Min. von eurer Unterkunft")
a(E1,"Scratch Patch Simon's Town","2520 Dido Valley Road","Simon's Town 7975","4.3","85","Regenwetter","Eintritt gratis / Steinbeutel ab R40","45-60 Min","Ja, ebenerdig","keines","Komplett überdacht und windgeschützt - Kinder suchen sich polierte Edelsteine aus einem Steinmeer","Als Regen- oder Windnotfall nach Boulders Beach (5 Min.)","Nein","https://www.scratchpatch.co.za/scratch-patch/","-34.1830","18.4325","0-2 Jahre: die Steine sind mundgerecht - permanente Aufsicht")
a(E1,"Bay Harbour Market","31 Harbour Road","Hout Bay, Cape Town 7806","4.5","843","Regenwetter / Essen","Eintritt gratis","1-1.5 Std","Bedingt - enge Gänge, Wickelraum vorhanden","keines","Indoor-Markt in einer alten Fischfabrik, komplett überdacht - Glacé, Waffeln, Crêpes","Mi oder Do 10:00-12:00","Nein","https://www.bayharbour.co.za/we-are-open/","-34.0490","18.3480","Mo + Di GESCHLOSSEN. Freitagabend Live-Musik - zu laut für Kinder. 8 Min. von der Unterkunft")
a(E1,"Oranjezicht City Farm Market","Granger Bay Boulevard","V&A Waterfront, Cape Town 8001","4.6","7136","Essen / Familie","Eintritt gratis","1-1.5 Std","Ja - neuer Standort barrierefrei","keines","Überdachte Holzscheune mit Pergolen, ebenerdig und breite Gänge","So 4.10. um 08:30 direkt zur Öffnung","Nein","https://ozcf.co.za/ozcfmarket/","-33.9022","18.4157","Mi 16-21, Sa 8-14, So 8:30-14. Der Mittwochtermin kollidiert mit der Abendroutine")

E2="2 | Paarl & Winelands (8.-11. Okt)"
a(E2,"Drakenstein Lion Park","Old Paarl Road (R101)","Klapmuts 7599","4.5","226","Tiere","R160 Erw. / R80 Kind (Ausländertarif)","1-1.5 Std","Eingeschränkt - Schotter- und Rasenwege","keines","Echtes Sanctuary ohne Streicheln; Löwen sind durch Doppelzaun oft nur ein bis zwei Meter entfernt - für Kinder enorm eindrücklich","09:30-11:00","Nein","https://lionrescue.org.za/","-33.79744","18.91160","Wenig Schatten - Hut und Sonnencreme. Picknickbereich vorhanden")
a(E2,"Exotic Animal World (ex Butterfly World)","R44","Klapmuts 7625","4.2","4593","Tiere / Regenwetter","ca. R150-170 p.P. (unbestätigt)","1-1.5 Std","Ja - befestigte Wege","keines","Freilaufende Lemuren, Erdmännchen, Ziegen und Enten zum Füttern - und eine überdachte Tropenhalle als einziges Schlechtwetter-Tierangebot der Gegend","09:30-11:00, wochentags ruhiger","Nein","https://exoticanimalworld.co.za/","-33.80090","18.87208","Schmetterlinge gibt es trotz des alten Namens nicht mehr")
a(E2,"Le Bonheur Krokodilfarm","Babylonstoren Road (R45)","Simondium 7670","4.4","1814","Tiere / Wasser","Teichtour R35-R62 je nach Alter","1.5-2 Std","Ja - überwiegend befestigt - Holzstege","Teichtour ohne Limit; Croc Cage Dive erst ab 9 Jahren","Alle 45 Minuten eine geführte Runde über die Stege - kurz, geführt, ohne Laufleistung; dazu Spielplatz und Ruderboote","10:00-11:30, dann Pizza vor Ort","Nein","https://lebonheuradventures.co.za/","-33.81837","18.94566","Offene Wasserflächen - Kind durchgehend an der Hand")
a(E2,"Babylonstoren Farmgarten","Klapmuts-Simondium Road (R45)","Simondium 7670","4.5","919","Natur / Tiere","R150 Erw. / Kinder unter 18 GRATIS","1.5-2 Std","Nur bedingt - Kieswege, Trage besser","keines","Ein essbares Labyrinth aus Obstbäumen, Entenreich und Gemüsebeeten; beim Farm Shop dürfen Kinder die Esel füttern - meist das Highlight","09:00-11:00 zur Öffnung","Garten nein, Restaurants ja","https://babylonstoren.com/visitor-information","-33.82385","18.92641","Nur Kartenzahlung. 25-30 Min. ab eurer Unterkunft")
a(E2,"Spice Route Destination","Suid-Agter-Paarl Road","Suider-Paarl 7646","4.4","720","Adventure / Essen","Eintritt frei, pro Aktivität zahlen","1.5-2 Std","Grösstenteils - Gelände liegt am Hang, teils steil","keines","Mehrere Spielplätze direkt neben den Restaurantterrassen - Eltern sitzen, Kinder toben. Wickeltisch vorhanden","09:30-11:30 oder 15:30-17:00","Nur fürs Essen","https://www.spiceroute.co.za/","-33.76406","18.91955","Schokoladen-Tasting und Keramikmalen vor Ort")
a(E2,"Fairview Ziegenturm","Suid-Agter-Paarl Road","Suider-Paarl 7646","4.4","1172","Tiere","Ziegenturm gratis","45-60 Min","Ja - gepflasterter Innenhof","keines","Der spiralförmige Turm mit den hochkletternden Ziegen ist genau das Format für 1- bis 5-Jährige: sofort sichtbar, gratis, keine Geduldsprobe","09:00-10:30, dann sind die Ziegen am aktivsten","Turm nein, Restaurant ja","https://www.fairview.co.za/","-33.77176","18.92423","Im Oktober ist Zickleinsaison - gute Chance auf Jungtiere")
a(E2,"Vergenoegd Löw Enten-Parade","1 Vergenoegd Road, ab R310","Faure / Somerset West 7131","4.3","380","Tiere","Parade GRATIS","Parade 15-30 Min","Ja","keines","Über 1000 Laufenten watscheln in geschlossener Kolonne durch das Gut in die Reben - laut, schnell und genau so lang wie die Aufmerksamkeitsspanne","09:00-Parade (die um 12:00 fällt in die Mittagspause)","Nein","https://vergenoegd.co.za/experiences/vergenoegd-low-runner-ducks","-34.03411","18.73929","45-50 Min. Fahrt - der weiteste Punkt. Estate öffnet erst 10:00, vor der Parade also keine Gastronomie")
a(E2,"Spier Elemental Play Garden","R310 Baden Powell Drive","Stellenbosch 7603","4.3","1235","Wasser / Natur","Geländezugang frei","2-3 Std, kürzbar","Ja - asphaltierte Wege, Wickelmöglichkeit","keines für Spielgarten; Segway ab 10","Spielgarten in vier Zonen mit Wasserlauf und Mosaik-Wasserspiel - die beste Wasseroption für ein 4-jähriges Kind ohne Poolrisiko","10:00-12:00","Nur Picknick","https://www.spier.co.za/","-33.97172","18.78424","Wasserspiele sind wetterabhängig, Anfang Oktober noch kühl - Wechselkleidung")
a(E2,"Bugz Family Playpark","56 Tarentaal Road, Joostenbergvlakte","Kraaifontein 7570","4.5","269","Adventure / Wasser","Kind 3-12 R190 / unter 3 GRATIS / Erwachsene R60","2-3 Std","Ja","Fahrgeschäfte 3-12; unter 3 nutzen Softplay, Streichelzoo und Wasserbereich gratis","Grösster Spielpark der Westkap mit Streichelzoo, Softplay und Wasserbereich; jede Station ist mit passendem Alter beschildert","10:00-12:00 (Fahrgeschäfte 10-16)","Nein, nur Kasse","https://www.bugzplaypark.co.za/park-info","-33.83325","18.73631","Fahrgeschäfte laufen primär am Wochenende - also Sa 10.10. oder So 11.10. Mitgebrachtes Essen nicht erlaubt")
a(E2,"Paarl Mountain Nature Reserve","Jan Phillips Mountain Drive","Paarl","4.6","207","Natur","Werktags GRATIS / Wochenende R30 p.P.","1-2 Std","Nein auf den Wegen - aber 25 km befahrbare Strassen zu den Picknickplätzen","keines","Drei Picknickplätze mit Toiletten, ein Damm mit Vögeln und riesige Granitkuppen - die kostenlose Natur-Dosis 15 Min. von der Unterkunft","08:00-10:00 oder 16:30-18:00","Nein","https://www.paarlonline.com/","-33.73271","18.94272","Bretagne Rock und Gordon's Rock sind ungesicherte Kletterei - nicht mit Kindern")
a(E2,"Afrikaanse Taalmonument","Gabbema Doordrift Street","Paarl 7646","4.3","458","Natur / Aussicht","R40 Erw.","45-60 Min","Ja - der bequemste Aussichtspunkt der Gegend","keines","Grosse offene Rasenflächen mit Blick bis zum Tafelberg, Bänke und Picknickplätze - Kinder können frei laufen","Früher Morgen oder später Nachmittag","Nein","https://taalmuseum.co.za/","-33.76577","18.94250","Café und Toiletten vorhanden")

E3="3 | Whale Coast (11.-14. Okt)"
a(E3,"Hermanus Cliff Path (Gearing's Point)","Gearing's Point, 71 Marine Drive","Hermanus 7200","4.5","23","Tiere / Natur","GRATIS","45-90 Min","Ja auf dem flachen Stadtabschnitt","keines","Die Wale kommen hier oft auf 20-50 m an die Felsen - Kinder sehen sie ohne Boot, ohne Seekrankheit, und man kann jederzeit abbrechen","08:30-11:00, ruhige See, wenig Wind","Nein","https://www.hermanus.co.za/popular-activities/whale-watching/","-34.42215","19.24393","Ungesicherte Steilkante. Weitere Top-Punkte per Auto: Sievers Point (-34.41063/19.26425) und Kwaaiwater")
a(E3,"Stony Point Pinguinkolonie","2411 Wallers Road","Betty's Bay 7141","4.7","983","Tiere","R45 Erw. / R30 Kind 4-17 / unter 4 gratis","45-90 Min","Ja mit Einschränkung - Holz-Boardwalk","keines","Brillenpinguine watscheln teils direkt neben dem Steg - die verlässlichste Tierbegegnung der Küste","09:00-11:00, ab 14:00 sehr windig","Nein","https://www.capenature.co.za/reserves/stony-point-nature-reserve","-34.37183","18.89407","1:35-1:45 h ab Stanford. TIPP: besser auf der Anfahrt von Paarl über die R44 einbauen statt als Tagestour")
a(E3,"Harold Porter Botanical Garden","Ecke Clarence Drive (R44) & Broadwith Road","Betty's Bay 7141","4.7","2340","Natur","R30 Erw. / Kinder unter 6 GRATIS","1-2 Std","Ja für unteren Garten und Disa-Trail","keines","Kurze ebene Rasen- und Teichwege, Zuckervögel in Reichweite, Café mit Milchshakes - der ruhige Gegenpol zum Pinguin-Trubel 4 km weiter","09:30-11:30, Oktober ist Blütehöhepunkt","Nein","https://www.sanbi.org/gardens/harold-porter","-34.35176","18.92690","Zigzag- und Oudebosch-Trail sind gesperrt")
a(E3,"Fernkloof Nature Reserve","Fir Avenue","Hermanus 7200","4.7","1503","Natur","GRATIS","45-75 Min","Ja für die angelegten Gartenwege","keines","Gratis, 10 Min. vom Cliff Path, mit Picknickplatz, Teich und Vögeln - der ideale Ein-Stunden-Füller vor der Mittagspause","Morgens, im Oktober blüht der Fynbos maximal","Nein","https://www.fernkloof.org.za/","-34.39453","19.26589","Nur die unteren Gärten - nicht die 50 km Bergtrails")
a(E3,"Grotto Beach + Lagune","Grotto Street","Voelklip, Hermanus 7200","4.6","928","Strand / Wasser","GRATIS","1-2 Std","Bis zur Strandkante ja, im Sand nein","keines","Einziger Blue-Flag-Strand der Gegend mit Spielplatz, Braai-Plätzen und Duschen; die Lagune an der Flussmündung ist flach, ruhig und wärmer als das Meer","09:00-11:30, nachmittags Wind","Nein","https://www.hermanus.co.za/nature/beaches","-34.41508","19.28899","Kinder NUR in die Lagune - das offene Meer hat Brandung und Rippströmungen. Im Oktober keine garantierte Rettungsschwimmer-Präsenz")
a(E3,"Lady Stanford Bootsfahrt Klein River","Jetty Ecke Du Toit St / Church St","Stanford 7210","4.8","22","Natur / Tiere","R280 p.P., Mindestumsatz R1120","ca. 2 Std","Nein an Bord, Zuweg eben","MINDESTALTER 0 - offiziell keine Grenze","Flusswasser statt Seegang: kein Wellenschlag, keine Seekrankheit. Zwei Decks, Bord-Toilette, flache Badestelle. Fischadler, Blaukraniche und Flamingos aus der Nähe","10:30-Abfahrt oder 15:30 nach der Mittagspause","Zwingend, Tel. 066 374 9386","https://ladystanford.activitar.com","-34.43856","19.45686","Die einzige geprüfte Bootsoption ohne Altersgrenze. Startet 4 km von eurer Unterkunft")
a(E3,"De Kelders Klippenpfad","De Kelders Gate, Walker Bay Nature Reserve","De Kelders, Gansbaai 7220","4.6","57","Natur","R65 Erw. / R45 Kind 4-17","30-45 Min für den oberen Pfad","Oberer Pfad teilweise ja","Höhle faktisch ab 6 Jahren","Der beste Landbeobachtungspunkt der Küste für Mutter-Kalb-Paare - die Bucht ist windgeschützt, die Wale liegen im Oktober oft direkt unterhalb","08:00-10:30 an einem trockenen Tag","Nein","https://www.capenature.co.za/reserves/walker-bay-nature-reserve","-34.54635","19.37873","Klipgat-Höhle: ca. 205 Stufen - mit Kind nicht machbar. Nur der obere Pfad. 26-30 Min. ab Stanford")
a(E3,"Platbos Forest","Grootbos Road, Abzweig R43","Gansbaai 7220","4.7","168","Natur / Regenwetter","R50 Erw. / R20 Kind (Ehrlichkeitskasse)","30-40 Min Teilstrecke möglich","Nein - Waldboden mit Wurzeln, Trage","keines","Weicher Waldboden, tiefer Schatten und 1000 Jahre alte Milkwood-Bäume - ein Elfenwald ohne Klippen, Verkehr oder Wasser","Nachmittag 14:30-16:30, im Wald bleibt es kühl","Nein","https://platbos.co.za/the-forest-trail","-34.56832","19.44790","Toiletten unbestätigt - vorher planen. Keine Hunde")
a(E3,"Kleinmond Strand & Lagune","19 Strand Street","Kleinmond 7195","4.3","59","Strand / Wasser","GRATIS","1-2 Std","Ja auf Rasen und Promenade","keines","Die Süsswasser-Lagune ist flach und warm zum Planschen, dazu Klettergerüst auf dem Rasen, Picknickbänke, Eisstand und Kanuverleih","Vormittag, nachmittags sehr windig","Nein","https://xplorio.com/kleinmond","-34.34412","19.03009","1:05 h ab Stanford - gut als Stopp auf der Rückfahrt von Betty's Bay. 500 m weiter: Rooisand mit wilden Pferden und flachem Pfad")
a(E3,"Stanford Hills Estate","Weltevrede Farm, Stanford Hills Road","Stanford 7210","4.2","43","Tiere / Essen","Kein Eintritt","1.5-2.5 Std","Ja - Rasen und ebene Terrasse","keines","Grosse Rasenfläche zum Toben, Enten und ein zahmes Schwein namens Crackling, kleiner Teich mit Ruderbooten - 8 Min. von eurer Unterkunft","Mittagessen 12:00-14:00, Kind schläft danach im Auto","Empfohlen","https://stanfordhills.co.za/","-34.42254","19.47420","Offener Farm-Teich ohne Zaun - Kinder nie unbeaufsichtigt")
a(E3,"Whale of a Time Play Park","Hermanus","Hermanus 7200","","","Regenwetter / Spielplatz","unbestätigt","1-2 Std","Ja","eigene Bereiche für kleinere Kinder","Moderner Indoor- und Outdoor-Spielpark mit Kletterelementen, Trampolinen und Rutschen; Erwachsene sitzen im angeschlossenen Restaurant","Regentag","Nein","https://whaleofatimeplay.co.za/","-34.4180","19.2350","Tipp aus eurem Schlechtwetter-PDF - Bewertung nicht geprüft")

E4="4 | Melozhori & Route 62 (14.-16. Okt)"
a(E4,"Melozhori Game Drive","R317, Stormsvlei","Stormsvlei 6730","","","Tiere","1 Fahrt bei 2+ Nächten INKLUSIVE, weitere R500 p.P.","ca. 2-2.5 Std","Nein - offener Safari-Wagen","von Melozhori nicht publiziert - vorab klären!","Raubtierfreies und malariafreies Reservat mit 38 Wildarten - Kinder sitzen bei den Eltern, keine Löwen, und man kann jederzeit abbrechen","Nachmittags ca. 16:00-18:00, nach der Mittagspause","Bei Anreise fixieren","https://www.melozhori.co.za/","-34.03703","20.08720","Mindestalter unbedingt vorab per Mail klären: info@melozhori.co.za / +27 66 595 7823")
a(E4,"Melozhori: Spaziergänge & E-Bikes","R317, Stormsvlei","Stormsvlei 6730","","","Natur","Spaziergänge gratis / E-Bike R850 pro Rad und Tag","frei wählbar","Teilweise - Schotterwege","keines","Das Reservat ist raubtierfrei, unbegleitete Spaziergänge sind erlaubt - dazu Vogelbeobachtung, Hängematte und ein Stargazing-Buch","Früher Morgen oder später Nachmittag","E-Bikes vorab","https://www.melozhori.co.za/","-34.03703","20.08720","Selbstfahren im Reservat ist NICHT erlaubt. Handy mitnehmen trotz schlechtem Empfang")
a(E4,"Bontebok National Park (Selbstfahrer)","N2, Swellendam","Swellendam 6740","4.3","1019","Tiere / Natur","R206 Erw. / R80 Kind 2-11 (International) / unter 2 gratis","1.5-2 Std Rundfahrt","Irrelevant - Aktivität findet im Auto statt","keines","Die perfekte Kinder-Safari: man bleibt im klimatisierten eigenen Auto, sieht Bontebok, Zebra und Schildkröten aus der Nähe und kann bei Quengeln sofort umdrehen","08:00-10:00 oder 15:30-17:30, Tore 07:00-19:00","Nein","https://www.sanparks.org/parks/bontebok","-34.05934","20.43076","Nach dem Breede-Hochwasser im Mai 2026 waren Flusspfade und Decks weggespült - Status vorab prüfen: +27 28 514 2735")
a(E4,"Marloth Nature Reserve - Koloniesbos","Zufahrt ab Swellendam, Parkplatz Koloniesbos","Swellendam 6740","4.4","145","Natur","R55 Erw. / R35 Kind 4-17, nur Bargeld","Waldschlaufe ca. 45 Min","Nein - Wurzeln und Steine, feste Schuhe nötig","keines","Kurze, komplett beschattete Runde durch indigenen Wald mit Bach - man ist nie weit vom Auto weg","09:00-11:00, Tor schliesst 16:00","Nein","https://www.capenature.co.za/reserves/marloth-nature-reserve","-33.96560","20.39200","Paviane - Essen nie unbeaufsichtigt lassen. Nicht die Duiwelsbos-Volltour nehmen")
a(E4,"Viljoensdrift Bootsfahrt Breede River","R317 am Breede River","Robertson 6705","4.5","558","Natur / Wasser","R120 Erw. / R50 Kind 3-12 / unter 3 gratis","Bootsfahrt 50 Min","Hof ja, Boot nein","keines publiziert","50 Minuten sind exakt die Aufmerksamkeitsspanne eines Kindes; ruhiges Flussboot, Enten und Reiher, danach Rasen zum Toben mit Deli-Essen","Check-in 60 Min. vor Abfahrt! Vormittag 10:00","ZWINGEND vorab online","https://viljoensdrift.co.za/river/","-33.87528","20.00262","Kein eigenes Picknick erlaubt. Google zeigte zwischenzeitlich 'temporarily closed' - vorher anrufen +27 23 615 1017")
a(E4,"Drostdy Museum Swellendam","18 Swellengrebel Street","Swellendam 6740","4.4","476","Regenwetter / Kultur","Ein Ticket für alle drei Gebäude, Preis unbestätigt","1-1.5 Std für die Kurzversion","Teilweise - Garten und Hof eben, Innenräume mit Stufen","keines","Das Kinder-Highlight ist nicht das Mobiliar, sondern der ummauerte Rosengarten, die Wassermühle und der Handwerkshof mit alten Karren - schattig und umzäunt","09:30-11:00","Nein","https://www.drostdymuseum.co.za/","-34.0187","20.4436","Plan B bei Regen. Öffnungszeiten ändern sich ohne Vorankündigung - anrufen +27 28 514 1138")
a(E4,"Four Cousins Robertson","3 Kromhout Road, Route 62","Robertson 6705","4.6","3328","Spielplatz / Essen","Kein Eintritt","1.5-2 Std","Ja","keines","Der grösste Spielplatz der Region direkt neben der Terrasse, dazu eigenes Kindermenü","Nach dem Mittagspause","Wochenende dringend","https://www.fourcousinsrestaurant.co.za/","-33.8028","19.8848","55-65 Min. ab Melozhori über zwei Pässe - kurvig")

E5="5 | Fahrtag N2 -> Plettenberg Bay (16. Okt)"
a(E5,"Bartolomeu Dias Museum","1 Market Street","Mossel Bay 6500","4.3","2143","Regenwetter / Kultur","widersprüchlich, ggf. gratis (unbestätigt)","1-1.5 Std","Ja - Komplex rollstuhlgängig","keines","Die lebensgrosse Karavelle im Trockendock und das Muschelmuseum sind auch für 2-5-Jährige begreifbar; ethnobotanischer Garten mit Meerblick, Schatten und Bänken","Erster Stopp ca. 10:15-11:30","Nein","http://www.diasmuseum.co.za/","-34.18036","22.14229","Umweg nur ca. 9 km / 12 Min. ab N2. Mo-Fr 09:00-16:45")
a(E5,"Redberry Farm","Geelhoutboom Road (ab R404), Blanco","George 6530","4.6","9030","Adventure / Familie","Kein Eintritt, Bezahlung pro Aktivität","gezielt 1-1.5 Std","Ja auf dem Hofgelände","keines für Zug, Erdbeerfeld und Kaninchen","Erdbeerpflücken ganzjährig, Minieisenbahn, Kaninchen, Heckenlabyrinth und Gokarts - der stärkste Kinderstopp der Strecke","09:00-10:30 oder 14:30-16:00","Nein (unter 10 Pers.)","https://www.redberryfarm.co.za/","-33.95846","22.38228","Mo-Sa 09:00-16:00, SONNTAGS ZU. Umweg ca. 10 km / 13 Min. Jeder Pflücker braucht einen eigenen Behälter")
a(E5,"Timberlake Organic Village","N2 zwischen Wilderness und Sedgefield, Kleinkrantz","Wilderness 6560","4.4","1411","Spielplatz / Regenwetter","Kein Eintritt","45-60 Min","Ja - zusammenhängendes Dorfgelände","keines","Der beste reine Zwischenstopp der Strecke: Spielplatz, Fairy Garden, schattige Sitzplätze, Bäckerei und mehrere Restaurants - direkt an der N2, kein Umweg","Mittagsstopp 12:30-13:30","Nein","https://www.timberlakeorganic.co.za/","-34.00097","22.68529","Naughty Monkey Cafe vor Ort (4.6, 507 Reviews), taeglich 08:15-16:30")
a(E5,"Acrobranch Garden Route - Acro-twigs","Timberlake Organic Village, N2","Wilderness 6560","4.8","196","Adventure","R130 p.P. für Acro-twigs","45-60 Min","Village ja, Parcours nein","ab 4 Jahren (Acro-twigs, 4-8 J.) - passt genau","Der einzige echte Abenteuerpunkt für euer Kind auf dieser Strecke: mit Gurt, Einweisung und eigenem Parcours für 4- bis 8-Jährige","14:00-15:30","Online, bargeldlos","https://acrobranch.co.za/outdoor-activity-parks/garden-route/","-34.00021","22.68411","Die anderen Kurse: ab 10 bzw. 11 Jahren und 1,40 m. Mi-So, Mo/Di zu")
a(E5,"Garden Route Botanical Garden","49 Caledon Street, Campher's Drift","George 6529","4.5","988","Natur","R15 p.P.","45-60 Min","Eingeschränkt - Hauptwege ja","keines","16 ha mit Damm, Seerosen, Vogelversteck und Picknickwiese - der günstigste Beinvertreter-Stopp mit nur 3 km Umweg","12:00-13:30 als Picknickstopp","Nein","https://botanicalgarden.org.za/","-33.94789","22.46369","Taeglich 07:30-17:30")
a(E5,"Knysna Elephant Park","N2 zwischen Knysna und Plettenberg Bay","Harkerville / Knysna 6600","4.6","5062","Tiere","Nicht-SA R460 Erw. / R285 Kind 5-14 / unter 5 GRATIS, Futtereimer R50","1 Std, Abfahrten alle 30 Min","Überwiegend ja","KEINES - Kinder jeden Alters","Die perfekte Ankunfts-Belohnung 20 Min. vor eurer Lodge: Elefanten aus wenigen Metern, Füttern mit Obst statt Reiten, halbstündliche Starts","Letzter Stopp ca. 14:30-16:00","Empfohlen","https://knysnaelephantpark.co.za/","-34.03669","23.27178","365 Tage, 09:00-16:00. Direkt an der Route, kein Umweg")

E6="6 | Plettenberg Bay (16.-20. Okt)"
a(E6,"Birds of Eden","Portion 11 & 12, Kirbywood Farm, Animal Alley","The Crags 6602","4.6","2466","Tiere / Regenwetter","R440 Erw. / R220 Kind 3-12 / unter 3 GRATIS","60-90 Min","Ja - über 1 km durchgehende Holzstege","keines","Die 2,3-ha-Kuppel ist regensicher und windgeschützt - die einzige Aktivität, die bei jedem Wetter funktioniert, und Vögel fliegen auf Augenhöhe am Wege vorbei","08:00-10:00, nicht nach 16:00 ankommen","Nein","https://www.birdsofeden.co.za/","-33.96443","23.48378","Kombiticket mit Monkeyland R704/R352, alle drei R900/R450")
a(E6,"Monkeyland","11 Askop Road, Animal Alley","The Crags 6602","4.5","2072","Tiere","R440 Erw. / R220 Kind 3-12 / unter 3 GRATIS","geführte Safari 45-60 Min","NEIN - Waldpfad und 128-m-Hängebrücke, Trage nötig","keines, aber Gruppentempo","Freilaufende Lemuren und Gibbons in Kopfhöhe begeistern schon 2-Jährige; die Tour ist kurz genug","Erste Tour 08:00-09:00","Empfohlen, feste Zeiten","https://www.monkeyland.co.za/","-33.96593","23.48175","Taschen nicht öffnen - Affen greifen zu")
a(E6,"Jukani Wildlife Sanctuary","N2, The Crags","The Crags 6602","4.3","759","Tiere","R440 Erw. / R220 Kind 3-12 / unter 3 GRATIS","60-90 Min","Ja - als rollstuhlgängig ausgewiesen","keines","Löwen, Tiger und Leoparden hinter Zaun statt in weiter Ferne - und die Wege sind so gut befestigt, dass auch müde Beine gut durchhalten","Später Nachmittag (Katzen aktiver) oder 08:30","Nein","https://www.jukani.co.za/","-33.97820","23.43623","Abfahrten alle 20 Min., letzte Tour 15:45")
a(E6,"Tenikwa - Wild Cat Experience","Forest Hall Road / Aandblom Street","The Crags 6602","4.8","2091","Tiere / Natur","R275 Erw. / R160 Kind 4-12 / 0-3 Jahre GRATIS","1 Std, Abfahrten alle 30 Min","Ja auf den Wegen - im Gehege muss das Kind getragen werden","keines - mit 4 auch die Forest-&-Fur-Tour möglich","Kleine Gruppen, nur eine Stunde, echte Rehabilitationsarbeit - Servale, Karakale und Geparden aus wenigen Metern. Ruhiger als die Nachbarn","09:00 erste Tour","Empfohlen","https://tenikwa.com/the-wild-cat-experience-2/","-33.96471","23.49099","Wild Cat Experience (1 Std.) ist die einfachste Wahl. 'Forest & Fur' (2 Std. Waldweg) ist ab 4 erlaubt, aber kein flacher Spazierweg. 'Cats in Conservation' erst ab 9")
a(E6,"Lawnwood Snake Sanctuary","N2, The Crags","The Crags 6602","4.8","519","Tiere / Regenwetter","ab ca. R300 (Kinderpreis unbestätigt)","1 Std Tour, mit Spielplatz 2 Std","Ja - flach und stufenlos","keines","Der unterschätzte Volltreffer: neben Schlangen gibt es Farmtiere, einen Spielplatz, Picknickwiese und einen Waldweg zum Fluss - falls die Reptilien nach 10 Minuten langweilig werden","Vormittags 09:00-11:00","Erst ab 15 Personen","https://www.sa-venues.com/things-to-do/gardenroute/lawnwood-snake-sanctuary/","-33.95999","23.47386","Beschatteter Parkplatz, Coffee Shop")
a(E6,"Raptor Rescue Plett","The Heath, N2 Harkerville","Plettenberg Bay 6600","4.9","53","Tiere","R190 Erw. / R120 Kind 3-12","Tour + Flugshow 1-1.5 Std","Teilweise - unbestätigt","keines","Die Flugvorführung mit freifliegenden Greifvögeln ist ein 20-Minuten-Spektakel auf Kinderniveau, mit Spielplatz und Picknickbereich daneben","Flugvorführung 12:00 oder 14:00","Erforderlich","https://raptorrescueplett.co.za/","-34.0430","23.2000","MONTAGS GESCHLOSSEN - für Mo 19.10. nicht einplanen")
a(E6,"Robberg Nature Reserve - Gap-Rundweg","Robberg Road","Plettenberg Bay 6600","4.8","2677","Natur","R75 Erw. / R55 Kind 4-17","2,1 km, mit Kind 60-75 Min","NEIN - Holztreppen, Fels- und Sandpfad. Feste Schuhe nötig","keines, aber Trittsicherheit der Eltern nötig","Der kürzeste der drei Rundwege bietet trotzdem Robbenkolonie, Wale in Küstennähe und dramatische Klippenblicke - in unter 90 Minuten","07:00-09:00: kühl, windstill, Wale nah","Nein","https://www.capenature.co.za/reserves/robberg-nature-reserve","-34.10425","23.39210","Kein Schatten, ungesicherte Klippenkanten. Die längeren Rundwege (5,5 und 9,2 km) sind nichts für Kinder")
a(E6,"Central Beach Plettenberg Bay","Hopwood Street / Beacon Isle","Plettenberg Bay 6600","4.5","271","Strand / Wasser","GRATIS","1-2 Std","Bis zur Strandkante ja","keines","Der geschützteste Badeplatz in Plett: die Bucht liegt im Windschatten der Beacon-Isle-Landzunge, Wellen deutlich kleiner, NSRI-Rettungsstation direkt am Strand","08:00-11:00, nachmittags Wind","Nein","https://www.plett-tourism.co.za/about/beaches/","-34.05797","23.37832","Blue-Flag-Saison startet erst 1. Dezember - Mitte Oktober keine bzw. nur Wochenend-Lifeguards. Wasser 16-18 Grad")
a(E6,"Keurbooms River Ferry","Keurbooms River, N2, Keurbooms River Nature Reserve","Keurboomstrand 6600","5.0","1","Natur / Wasser","R675 Erw. / R505 Kind 2-12","2-2.5 Std - am oberen Limit","Bis zum Steg ja","keines angegeben","Ruhiges Flusswasser statt Brandung - kein Seegang. Der Halt an einem Flussstrand zum Buddeln bricht die Fahrt genau richtig","Vormittagsfahrt, Abfahrten richten sich nach der Tide","ZWINGEND, 069 733 0410","https://keurboomsriverferries.co.za/","-34.00182","23.40231","Nur 1 Bewertung (Betreiberwechsel 2024). Toiletten an Bord unbestätigt - bei 2,5 Std. mit Kind vorher klären. Selbstverpflegung nötig")
a(E6,"Knysna Heads - East Head Viewpoint","Ende George Rex Drive, The Heads","Knysna 6571","4.6","2613","Natur","GRATIS","20-45 Min","Ja am Hauptaussichtsdeck","keines","Maximaler Wow-Effekt für minimalen Aufwand: ihr parkt praktisch am Aussichtspunkt, seht Schiffe durch die Felsenpassage und im Oktober oft Wale","Nach dem Mittagspause","Nein","https://www.visitknysna.co.za/","-34.07655","23.05990","Ungesicherte Felskanten - Kinder an der Hand. 50-58 Min. ab Emily Moon")
a(E6,"Old Nick Village","Old Nick Village, N2","Plettenberg Bay 6600","4.0","124","Spielplatz / Regenwetter","GRATIS","1-1.5 Std","Ja","keines","Naturspielplatz mit Tunneln, Rutschen und Holzbalken, dazu Gärten, Café und Weberei - nur 3 km von eurer Lodge","Taeglich 09:00-17:00, Mittwochsmarkt 09:00-14:00","Nein","https://oldnickvillage.co.za/","-34.03495","23.37301","Knapp unter 4.2, aber die beste Schlechtwetter-Reserve mit kurzem Anfahrtsweg")
a(E6,"KidZone Indoor Play Centre","Forest Gate","Plettenberg Bay","","","Regenwetter / Spielplatz","unbestätigt","1-2 Std","Ja","Angebote für kleinere und grössere Kinder","Vollständig überdachter Indoor-Spielbereich mit Klettergerüsten, Rutschen und Softplay; Restaurant direkt daneben","Regentag","Nein","https://forestgate.co.za/kidzone-indoor-play-centre/","-34.0510","23.3560","Tipp aus eurem Schlechtwetter-PDF - Bewertung nicht geprüft")
a(E6,"Storms River Suspension Bridge","Storms River Mouth Rest Camp, Tsitsikamma","Storms River, Eastern Cape","4.4","1093","Natur / Adventure","International R367 Erw. / Kind 2-11 halber Preis / unter 2 gratis","Hin und zurück ca. 1 Std","DEFINITIV NEIN - ca. 200 zum Teil steile Stufen. Feste Schuhe nötig","keines, aber Tragen zwingend","Der Steg über die Flussschlucht ist das spektakulärste Naturerlebnis der Region","Vor 10:00","Nein","https://www.sanparks.org/parks/garden-route","-34.02212","23.88591","130 km hin und zurück - der schwächste Zeit-Nutzen-Faktor der Etappe. Status 2026 prüfen: evtl. nur eine der drei Brücken offen")

E7="7 | Sundays River Valley / Addo (20.-23. Okt)"
a(E7,"Addo Elephant NP - Selbstfahrer-Safari","Main Gate, R335","Addo 6105","4.5","3095","Tiere / Natur","International R492 Erw. / R246 Kind 2-11 / unter 2 GRATIS","frei wählbar, für Kinder 1.5-2 Std Schleife","Irrelevant - Aktivität im eigenen Auto","KEINES für Selbstfahrer","Im eigenen Auto: Klimaanlage, Snacks, Windelwechsel und ein schlafendes Kind sind kein Problem. Elefanten stehen oft direkt an der Strasse","06:45 am Tor (Öffnung 07:00) bis 09:30, oder 15:30-18:00","Nein","https://www.sanparks.org/parks/addo-elephant","-33.44394","25.74622","AUSWEIS MITBRINGEN - Pass oder Führerschein ist Pflicht. Nur 18-22 Min. von Woodall")
a(E7,"Addo Main Camp - Wasserloch & Underground Hide","Addo Rest Camp, R335","Addo 6105","4.5","3095","Tiere / Regenwetter","im Eintritt enthalten","45-90 Min","Ja - Camp-Wege befestigt, Hide über Rampe","keines","Tiere kommen zu euch, statt dass ihr sie sucht. Der Underground Hide bringt Elefanten auf Augenhöhe wenige Meter vor die Nase","Später Nachmittag 16:00-18:00","Nein","https://www.sanparks.org/parks/addo-elephant/camps/addo","-33.44394","25.74622","Wasserloch ist flutlichtbeleuchtet. Restaurant, Pool, Shop, Picknickplätze vorhanden")
a(E7,"Daniell Cheetah Project","R75","Kirkwood 6120","4.3","269","Tiere","ca. R100-R130 p.P. (unbestätigt)","Predator Tour genau 1 Std","Teilweise - Farmuntergrund","keines für die Predator Tour; Cheetah Walk ab 14","Zusätzlich zu Geparden und Löwen gibt es einen Streichelbereich mit Kaninchen und Meerschweinchen sowie handaufgezogene Kudus - das funktioniert bei 2-5-Jährigen besser","Tour 09:00 oder 10:00, Rückfahrt = Autoschlaf","Nicht nötig","https://daniellcheetahproject.com/tours/","-33.4640","25.3830","Ca. 45 Min. ab Woodall. Preis nirgends publiziert - anrufen +27 66 3857 098")
a(E7,"Addo Wildlife Centre","R335 Main Road","Addo 6105","4.6","95","Tiere / Regenwetter","R20 pro Person","45-60 Min","Überwiegend ja","keines","Für R20 sehr kurze, sehr nahe Tierbegegnungen: Papageien, Geckos, Eulen, Äffchen und eine begehbare Voliere - der perfekte Füller zwischen Mittagspause und Abendessen","16:00-17:00","Nein","https://addowildlife.co.za/wildlife-centre","-33.5240","25.6919","Nur 5 Min. von Woodall. Restaurant Tangelo im selben Haus")
a(E7,"Sundays River Adventures - Kurz-Bootsfahrt","A Taste of Africa Restaurant, N2","Colchester 6175","4.6","76","Natur / Wasser","Preis unbestätigt, Mindestteilnehmer 2","1.5 Std - die kürzeste Bootsoption der Region","Nein - Boot","MINDESTALTER 0","Halb so lang wie die grosse Cruise, mit Restaurant und Spielmöglichkeit am Startpunkt - falls die Fahrt zu viel wird, ist der Ausstieg schnell erreicht","Vormittags, 45 Min. vor Start eintreffen","Ja, +27 41 492 2355","https://sundaze.activitar.com","-33.7000","25.8300","Die kleinkindtauglichere Alternative zur 2,5-Std.-Cruise")
a(E7,"Addo Cruises & Sand Sledding","Cannonville","Colchester 6175","4.9","129","Natur / Adventure / Wasser","Scenic Cruise R760 Erw. / R380 Kind 5-12","2.5 Std","Nein - Boot","kein offizielles; unter 5 nicht im Tarif - vorab klären","Doppeldecker-Ponton mit Toilette an Bord, ruhiges Ästuarwasser, Fischadler und Affen - plus die goldenen Alexandria-Dünen als Riesenrutsche","09:00-Abfahrt, zurück ca. 11:30","ZWINGEND, min. 4 Erwachsene","https://addocruises.co.za/","-33.6900","25.8200","Bei Wind entfällt die Tour. Sandboarding: ein Rezensent fuhr mit seinem 4-Jährigen gemeinsam auf dem Board")
a(E7,"Kragga Kamma Game Park","Kragga Kamma Road, Colleen Glen","Gqeberha 6018","4.4","765","Tiere","Selbstfahrer R140 Erw. / R70 Kind 3-17 / unter 3 GRATIS","Selbstfahrt 1-1.5 Std","Irrelevant - eigenes Auto","KEINES beim Selbstfahren","Nur 200 ha, das heisst garantierte Sichtungen von Nashorn, Giraffe, Zebra und Gepard in unter einer Stunde - kein frustrierendes Suchen","Toröffnung 08:00 oder ab 15:30","Selbstfahren ohne Buchung","https://www.kraggakamma.co.za/","-33.9720","25.4530","Taeglich ausser 25. Dezember - also auch am Abreise-Montag offen. GPS im Navi gegenprüfen")

E8="8 | Lalibela & Gqeberha (23.-26. Okt)"
a(E8,"Lalibela Mark's Camp - Safari Drives","Lalibela Game Reserve, N2","Paterson 6130","","","Tiere / Adventure","im All-Inclusive enthalten","Erwachsene 3-4 Std, Kinder-Drives deutlich kürzer","Nein - offenes Fahrzeug","ab 2 Jahren - mit 4 also dabei","Familien mit ähnlich alten Kindern werden zusammen eingeteilt, damit das Tempo passt. Kinder-Drives fahren im eigenen Fahrzeug mit eigenem Ranger","Morgen-Drive ca. 06:00, Nachmittag ca. 16:00 - der Mittagspause bleibt frei","Im Paket, Kinderprogramm vorab anmelden","https://lalibela.travel/lodges/marks-camp","-33.3000","26.0600","Mit 4 Jahren fährt euer Kind mit. Kinderbetreuung während der Mahlzeiten der Erwachsenen ist im Preis enthalten")
a(E8,"Lalibela Kinderprogramm (Tiny Trackers)","Lalibela Game Reserve, N2","Paterson 6130","","","Familie","im All-Inclusive enthalten","zwischen den Mahlzeiten und Drives","Ja im Camp","ab 2 Jahren","Schnitzeljagden, Basteln, Steine bemalen, Vögel beobachten und Tierspuren bestimmen; bei gutem Wetter geführte Spaziergänge und Fussball. Eltern dürfen mitmachen oder ausruhen","10:00-16:00, wenn auf Safari ohnehin nichts passiert","Vorab anmelden","https://lalibela.travel/lodges/marks-camp","-33.3000","26.0600","Kinder unter 8 bekommen ein eigenes Kindermenü und essen früher. Camp ist diskret eingezäunt")
a(E8,"SANCCOB Pinguin-Rehabilitation","Marine Drive, Cape Recife Nature Reserve","Summerstrand, Gqeberha 6011","4.5","221","Tiere / Regenwetter","International R75 Erw. / R30 Kind unter 12","Touren alle 30 Min, 30-45 Min","Voraussichtlich ja (unbestätigt)","keines","Afrikanische Pinguine aus wenigen Metern, Fütterung im Home Pen um 09:30 und 14:30 - laut, lebendig und genau richtig kurz","09:30 Fütterung - passt perfekt vor einen Nachmittagsflug","Nicht zwingend","https://sanccob.co.za/sanccob-tours","-34.01320","25.69069","Nur ca. 15 Min. vom Flughafen. Montags-Öffnung unbestätigt - anrufen +27 41 583 1830")
a(E8,"Cape Recife Nature Reserve","Off Marine Drive, neben Pine Lodge","Summerstrand, Gqeberha 6001","4.4","8","Natur / Strand","Permit ab R32 pro Fahrzeug - GRATIS mit SANCCOB-Nachweis","30-60 Min","Nur befestigter Zufahrtsbereich","keines","Direkt mit SANCCOB kombinierbar, mit Leuchtturm von 1851 und Vogel-Hide - ein kurzer Spaziergang, bei dem es alle paar Meter etwas zu zeigen gibt","08:00-10:00, im Anschluss an SANCCOB","Nein, Permit vor Ort","https://www.nmbt.co.za/","-34.01347","25.69131","Reservat 08:00-16:00")
a(E8,"Grass Roof Farm - Kids Area","792 Heron Road, Lovemore Park","Gqeberha 6070","4.3","4505","Spielplatz / Essen / Regenwetter","Kids Area 1 GRATIS / Kids Area 2 R80 pro Kind","1.5-2 Std","Ja - ebenerdig und rollstuhlgängig","keines","Kids Area 1 liegt direkt neben den Tischen (Jungle Gym, Riesenschaukel, Fahrradbahn) - Eltern essen in Ruhe und sehen die Kinder","Vor dem Flug, taeglich 08:00-16:30","Nein","https://www.grassroof.co.za/kids-area","-34.01205","25.49638","Kids Area 2 (Hüpfburg, Pool, Zug) öffnet werktags NUR in den Schulferien - am 26.10. voraussichtlich zu")
a(E8,"Kings Beach","Beach Road, Humewood","Gqeberha 6001","4.6","329","Strand","GRATIS","1-2 Std","Ja - Promenade befestigt","keines","Der am besten ausgestattete Familienstrand der Bucht: Rettungsschwimmer, Umkleiden, Duschen, viel Parkplatz und breites, flach abfallendes Wasser","Vor 10:00 oder nach 16:00","Nein","https://www.nmbt.co.za/","-33.9770","25.6440","Wasser im Oktober ca. 18-19 Grad - eher Buddeln als Baden")
a(E8,"Pollok Beach Gezeitentümpel","Marine Drive","Summerstrand, Gqeberha 6001","4.4","569","Strand / Wasser","GRATIS","1-1.5 Std","Ja - Promenade befestigt","keines","Warme, knietiefe Gezeitentümpel voller kleiner Meerestiere - direkt gegenüber dem Something Good Roadhouse mit Spielplatz und Eisdiele","Bei Ebbe - Gezeitentabelle prüfen","Nein","https://www.somethinggoodroadhouse.co.za/","-34.0180","25.6600","Falls das Kind kippt: das Roadhouse hat Autoservice ans Fahrzeug")
