# -*- coding: utf-8 -*-
# Tagesplan. items: (zeit, art, titel, detail)
# art: fahrt | buchung | checkin | checkout | tipp | warnung | frei
DAYS = [
("So 4. Okt","1","Ankunft Kapstadt","Adamsgarth Guesthouse, Hout Bay","ankunft",[
 ("","fahrt","Flughafen CPT → Adamsgarth Guesthouse","33 km · Google 35–40 Min · <b>realistisch 50–60 Min</b> · Route N2 → M3 → Constantia Nek → Hout Bay. Dazu Mietwagenübernahme in CPT: realistisch 45–90 Min extra.",130),
 ("14:00","checkin","Check-in Adamsgarth Guesthouse","26 Mount Rhodes Drive, Hout Bay – am Hang oberhalb des Tals, nicht im Zentrum."),
 ("","tipp","Ankunftstag ruhig halten","Hout Bay Hafen ist 8–10 Min. entfernt: Mariner's Wharf, Strand, Dunes Restaurant mit eingezäuntem Spielplatz. Mehr braucht der erste Tag nicht."),
 ("08:30","tipp","Optional: Oranjezicht Market","So 08:30–14:00, Granger Bay. Nur wenn ihr früh landet und noch Energie habt."),
]),
("Mo 5. Okt","1","Kapstadt","Halbinsel-Tag","stand",[
 ("08:00","tipp","Boulders Beach Pinguine","55–65 Min ab Hout Bay über die M4 (oder 31 km über Chapman's Peak, Maut ca. R60). Früh da sein – der Parkplatz ist klein.",90),
 ("","tipp","Danach St James / Dalebrook Gezeitenbecken","Nur 15 Min. weiter. Ummauerte Becken ohne Brandung – der sicherste Badeplatz für Kinder."),
 ("13:00","frei","Pause","Auf der Halbinselstrecke schläft es sich im Auto gut.",90),
 ("14:45","tipp","Scratch Patch Simon's Town oder Muizenberg Beach","Scratch Patch: überdacht, 45 Min, Edelsteine sammeln – 5 Min von Boulders. Muizenberg: die bunten Badehäuschen und flaches, wärmeres Wasser als am Atlantik.",120),
 ("","warnung","Blue Train Park heute geschlossen","Montags zu (ausser in Schulferien) – Term 4 startet am 6.10., also heute wahrscheinlich zu."),
]),
("Di 6. Okt","1","Kapstadt","Stadt-Tag","stand",[
 ("08:00","tipp","Tafelberg-Seilbahn, erste Fahrt","35–45 Min ab Hout Bay. <b>Am Morgen Betriebsstatus prüfen</b> – bei Wind wird geschlossen. Tickets vorab online.",120),
 ("","tipp","Danach Green Point Urban Park","Tot-Lot-Spielplatz für 1–6 Jahre, gratis, durchgehend geteert."),
 ("13:00","frei","Pause","",90),
 ("14:45","tipp","Sea Point Promenade und Pavilion","11 km flacher Asphaltweg mit Spielplätzen. Das Kinderbecken im Pavilion ist 40 cm tief und beaufsichtigt. Bis 17:00 gut machbar.",135),
]),
("Mi 7. Okt","1","Kapstadt","Nahbereich Hout Bay","stand",[
 ("09:00","tipp","Duiker Island Robbenfahrt","40 Minuten – die kürzeste Tierbeobachtungstour der Region. Hafen 8 Min. von der Unterkunft.",60),
 ("10:00","tipp","Bay Harbour Market","Mi + Do 09:30–17:00, überdacht. Gleicher Hafen, kein zweiter Weg."),
 ("11:00","tipp","Alternativ World of Birds","10 Min. entfernt, Pinguinfütterung 11:30, Monkey Jungle 11:30–13:00, eigener Kinder-Spielplatz."),
 ("13:00","frei","Pause","",90),
]),
("Do 8. Okt","2","Kapstadt → Paarl","Adara Palmiet Valley Estate","fahrt",[
 ("10:00","checkout","Check-out Adamsgarth",""),
 ("10:15","fahrt","Hout Bay → Adara Palmiet Valley, Paarl","79 km · Google 60–65 Min · <b>realistisch 1:20–1:30 h</b> · M6 → Kloof Nek → City Bowl → N1. <b>Zur Rushhour besser</b> über Constantia Nek → M3 → N2 → N1 (84 km, ~75 Min), das umgeht die Innenstadt.",90),
 ("","tipp","Unterwegs: Kirstenbosch","Liegt fast auf dem Weg, wenn ihr über Constantia Nek fahrt. 1,5 Std. einplanen."),
 ("14:00","checkin","Check-in Adara Palmiet Valley","Sonstraal Road, Klein Drakenstein, Paarl – ca. 5 km östlich von Paarl."),
 ("18:30","buchung","Abendessen Adara Restaurant","GEBUCHT · in eurer Unterkunft, keine Fahrt nötig."),
]),
("Fr 9. Okt","2","Paarl","Winelands","stand",[
 ("09:00","tipp","Fairview Ziegenturm oder Le Bonheur Krokodile","Fairview: 15 Min, gratis, 45 Min. Le Bonheur: 20 Min, geführte Runde alle 45 Min."),
 ("11:45","fahrt","Losfahren zum Boschendal Deli","22 km · <b>28–32 Min mit Kindern</b> · N1 → R45 → R310. Geteert, kein Pass.",35),
 ("12:30","buchung","Mittagessen Deli Boschendal","GEBUCHT · Danach: Tree-House-Spielplatz und Pumptrack auf dem Gelände – gute Gelegenheit zum Austoben vor der Rückfahrt."),
 ("15:00","tipp","Zurück über Franschhoek","Der Franschhoek Pass hat oben einen Aussichtspunkt mit Blick über das Tal. Oder direkt zurück und Pool in der Unterkunft.",120),
]),
("Sa 10. Okt","2","Paarl","Winelands","stand",[
 ("09:00","tipp","Vergenoegd Enten-Parade","<b>09:00-Parade</b> (die um 12:00 fällt in die Mittagspause). 45–50 Min. Fahrt – früh los. Gratis, dauert 15–30 Min.",60),
 ("11:40","fahrt","Losfahren zu Tokara","28,5 km · <b>38–45 Min mit Kindern</b> · über den Helshoogte Pass. <b>Kurvenreich</b> – bei Reiseübelkeit vorsorgen.",45),
 ("12:30","buchung","Mittagessen Tokara Delicatessen","GEBUCHT · Klettergerüst, viel Auslauf und Pfauen auf dem Gelände."),
 ("14:45","tipp","Spier Elemental Play Garden","Auf dem Rückweg: Spielgarten in vier Zonen mit Wasserlauf und Mosaik-Brunnen, dazu Picknickwiesen am Fluss. Bis 17:00 offen.",135),
 ("","tipp","Alternative statt Vergenoegd: Spier","Elemental Play Garden mit Wasserspiel, liegt Richtung Stellenbosch – lässt sich mit Tokara zu einem Bogen verbinden."),
]),
("So 11. Okt","3","Paarl → Whale Coast","Rivergate Guest Farm, Stanford","fahrt",[
 ("10:00","checkout","Check-out Adara",""),
 ("10:15","fahrt","Paarl → Stanford (direkt)","158 km · Google 2:00–2:10 h · <b>realistisch 3:00–3:15 h mit einer Pause</b> · N1 → R300 → N2 über Sir Lowry's Pass → R43 über Hermanus. Komplett geteert.",195),
 ("","tipp","EMPFEHLUNG: Umweg über Stony Point","Statt direkt: N2 → Abfahrt Gordon's Bay → <b>R44 Küstenstrasse</b> → Stony Point Pinguine (Betty's Bay) → Kleinmond → Hermanus → Stanford. 174 km statt 158, ca. 2:40 h reine Fahrzeit statt 2:05. Ihr spart euch damit die 3,5-Stunden-Tagestour nach Betty's Bay und die Kinder haben genau zur richtigen Zeit eine Pause."),
 ("","tipp","Stopp: Dassiesfontein Farm Stall","An der N2 zwischen Bot River und Caledon, mit Spielbereich."),
 ("14:00","checkin","Check-in Rivergate Guest Farm","Wortelgat Road, 2 km ausserhalb Stanford am Klein River."),
]),
("Mo 12. Okt","3","Whale Coast","Hermanus","stand",[
 ("08:30","tipp","Hermanus Cliff Path, Gearing's Point","35–40 Min ab Stanford. Wale oft auf 20–50 m an den Felsen – gratis, flach begehbar, jederzeit abbrechbar."),
 ("","tipp","Danach Fernkloof Nature Reserve","10 Min. weiter, gratis, Picknickplatz und Teich."),
 ("13:00","frei","Pause","",90),
 ("15:30","tipp","Stanford Hills Estate","8 Min. von der Unterkunft. Rasen, Enten, ein zahmes Schwein und ein Teich mit Ruderbooten."),
]),
("Di 13. Okt","3","Whale Coast","Whale Watching","stand",[
 ("07:45","fahrt","Losfahren zum Whale Watching","Falls die Tour ab Hermanus New Harbour startet: 35–40 Min ab Rivergate, Check-in meist 30 Min. vorher.",45),
 ("09:00","buchung","Whale Watching 09:00–12:00","GEBUCHT · 3 Stunden."),
 ("","warnung","Prüft das mit den Kindern","Die Hermanus-Anbieter verlangen für <b>alle Kinder unter 13 Jahren eine Schwimmweste während der ganzen Fahrt</b> – fragt vorab nach der Grösse für ein 4-jähriges Kind. <b>Drei Stunden ohne Ausstiegsmöglichkeit sind lang</b>: erkundigt euch, ob eine kürzere Tour geht. Falls es kippt, ist die Landbeobachtung eine vollwertige Alternative – im Oktober liegen die Wale oft 20–50 m vor den Felsen."),
 ("","tipp","Landalternative: De Kelders Klippenpfad","26–30 Min ab Stanford. Der beste Landbeobachtungspunkt der Küste für Mutter-Kalb-Paare – windgeschützt, oberer Pfad teilweise mit  machbar."),
 ("14:30","tipp","Platbos Forest oder Grotto Beach","Platbos: weicher Waldboden, tiefer Schatten, 1000 Jahre alte Milkwood-Bäume, 30-40 Min Runde. Grotto Beach: flache Lagune, Spielplatz, Duschen.",150),
]),
("Mi 14. Okt","4","Whale Coast → Melozhori","Melozhori Private Game Reserve","fahrt",[
 ("10:00","checkout","Check-out Rivergate",""),
 ("10:15","fahrt","Stanford → Melozhori","91 km · Google 1:05–1:15 h · <b>realistisch 1:35–1:45 h</b> · R326 über Akkedisberg-Pass (geteert) → N2 → Abfahrt Stormsvlei → R317 6 km nordwärts.",105),
 ("","warnung","Letzte Versorgung vor der Lodge","Stormsvlei Farm Stall am N2-Abzweig ist <b>dauerhaft geschlossen</b>. Letzte Einkaufsmöglichkeit: Riviersonderend oder Caledon. Die Lodge ist Selbstverpflegung mit Halbpension-Option – Semi-Catering (R850/Erw., R350/Kind unter 8) muss vorab bestellt sein."),
 ("14:00","checkin","Check-in Melozhori Cottage","Zwei En-Suite-Schlafzimmer, Pizzaofen, Braai, Hot Tub, kleiner Splash Pool. Brot und Früchte zur Ankunft."),
 ("16:00","tipp","Game Drive","Eine geführte Fahrt ist bei 2+ Nächten inklusive. <b>Mindestalter vorab klären</b>: info@melozhori.co.za",150),
]),
("Do 15. Okt","4","Melozhori","Overberg","stand",[
 ("","tipp","Auf dem Reservat bleiben","Melozhori ist raubtierfrei – unbegleitete Spaziergänge und Vogelbeobachtung sind erlaubt. Selbstfahren im Reservat ist nicht gestattet."),
 ("09:00","tipp","Optional: Bontebok National Park","40–48 Min ab Melozhori. Selbstfahrer-Safari im eigenen Auto – die entspannteste Safariform mit Kindern. Status nach dem Hochwasser 2026 vorab prüfen: +27 28 514 2735."),
 ("","tipp","Optional: Swellendam","40–48 Min. Drostdy Museum mit ummauertem Rosengarten und Handwerkshof, dazu Grace + Merci oder Woodpecker Pizzadeli."),
 ("","warnung","Robertson ist weiter als es aussieht","42 km, aber 55–65 Min – zwei Pässe, kurvig. Four Cousins hat zwar den grössten Spielplatz der Region, aber überlegt, ob sich die Fahrt an einem von zwei Tagen lohnt."),
]),
("Fr 16. Okt","5","Melozhori → Plettenberg Bay","Der lange Fahrtag","fahrt",[
 ("","warnung","Das ist die härteste Etappe der Reise","350 km · Google 3:45–4:00 h · <b>realistisch 5:45–6:30 h mit zwei Pausen</b>. Bei Check-out um 10:00 wärt ihr erst gegen 16:30 da. <b>Fahrt früher los – 07:30 statt 10:00.</b> Die R62-Variante über Oudtshoorn wäre 420–466 km und ist an einem Tag mit Kindern nicht machbar."),
 ("07:30","fahrt","Melozhori → Plettenberg Bay","R317 → N2 durchgehend ostwärts: Swellendam – Riversdale – Mossel Bay – George – Wilderness – Knysna – Plett. Komplett geteert, gut ausgebaut.",390),
 ("10:15","tipp","Stopp 1: Dias Museum Mossel Bay","Umweg nur 9 km. Lebensgrosse Karavelle im Trockendock, Garten mit Meerblick. Oder: Die Skeerhok Padstal bei Heidelberg (4,7) bzw. Ou Meul Riversdale mit grossem Spielplatz.",75),
 ("13:00","tipp","Stopp 2: Timberlake Village","Direkt an der N2, kein Umweg. Spielplatz, Bäckerei, Naughty Monkey Cafe. Für ein 4-jähriges Kind: Acrobranch „Acro-twigs\" (ab 4 Jahren, R130, 45 Min).",75),
 ("15:00","tipp","Stopp 3: Knysna Elephant Park","20 Min. vor eurer Lodge, direkt an der N2. Kein Mindestalter, unter 5 gratis, Touren alle 30 Min bis 15:30. Die perfekte Ankunfts-Belohnung.",75),
 ("16:45","checkin","Check-in Emily Moon River Lodge","Rietvlei Road, nördlich der Stadt am Bitou River."),
 ("","warnung","Redberry Farm und Elephant Park gehen nicht beide","Beide schliessen um 16:00. Entweder Erdbeeren pflücken in George (Umweg 10 km, Mo–Sa 9–16) oder Elefanten kurz vor Plett."),
]),
("Sa 17. Okt","6","Plettenberg Bay","Animal Alley","stand",[
 ("08:00","tipp","Birds of Eden","25–30 Min. Überkuppelt, also wind- und regensicher, über 1 km durchgehende Holzstege – die bequemste Aktivität der Etappe.",120),
 ("","tipp","Kombiticket prüfen","Birds of Eden + Monkeyland R704/R352, alle drei mit Jukani R900/R450. Realistisch schafft ihr maximal zwei pro Tag – fragt vorher, ob das Triptic auf zwei Tage aufteilbar ist."),
 ("11:30","tipp","Mittagessen Bramon Wine Estate","Direkt nebenan, Tische zwischen den Reben, viel Platz zum Laufen. Nur 11:00–16:00.",90),
 ("13:00","frei","Pause","",90),
]),
("So 18. Okt","6","Plettenberg Bay","Strand & Robberg","stand",[
 ("07:30","tipp","Robberg Gap-Rundweg","2,1 km, mit Kind 60–75 Min. <b>Holztreppen und Felspfad</b> – feste Schuhe, ein 4-Jähriges schafft das mit Pausen. Robbenkolonie und Wale in Küstennähe. Früh: kühl, windstill.",90),
 ("10:00","tipp","Central Beach","Der geschützteste Badeplatz in Plett, im Windschatten der Beacon-Isle-Landzunge."),
 ("","warnung","Baden im Oktober","Blue-Flag-Saison startet erst am 1. Dezember – jetzt keine oder nur Wochenend-Lifeguards, Wasser 16–18 °C. Knietief und in Armlänge."),
 ("15:30","tipp","Nachmittags Jukani","Katzen sind später aktiver, Wege sind flach begehbar."),
]),
("Mo 19. Okt","6","Plettenberg Bay","Knysna","stand",[
 ("09:00","tipp","Knysna Elephant Park","22–26 Min, direkt an der N2. Falls ihr am Fahrtag nicht dazugekommen seid."),
 ("11:00","tipp","Knysna Heads, East Head","50–58 Min ab Emily Moon – die letzten 7 km durch die Stadt kosten mehr Zeit als die N2-Distanz vermuten lässt. Parken praktisch am Aussichtspunkt."),
 ("","warnung","Raptor Rescue heute geschlossen","Montags zu. Auch île de pain in Knysna hat montags zu."),
 ("14:30","tipp","Knysna Waterfront oder Freshline Fisheries","Boote, Enten und Fischtheke direkt am Wasser. Danach Heimfahrt vor dem Dunkelwerden.",120),
]),
("Di 20. Okt","7","Plettenberg Bay → Addo","Woodall Country House & Spa","fahrt",[
 ("09:00","checkout","Check-out Emily Moon (bis 10:00)",""),
 ("09:15","fahrt","Plettenberg Bay → Woodall, Addo","272–311 km · Google 3:05–3:30 h · <b>realistisch 4:45–5:15 h mit zwei Pausen</b> · Empfohlen: N2 durchgehend bis Gqeberha, weiter Richtung Makhanda, Abfahrt 761 auf die R335, 43 km nordwärts durch Addo Village.",315),
 ("","tipp","Stopp: Nanaga Farm Stall","Am Kreuz N10/R72, berühmt für Roosterkoek und Ananassaft, mit Spielbereich und grossen Rasenflächen."),
 ("","warnung","Letzte 1,2 km Schotter","Rechts von der R335 am Woodall-Schild abbiegen, nach 40 m nochmals rechts vor dem Elephant House, dann 1,2 km. Für einen Pkw problemlos, bei Regen langsam. <b>Das ist der einzige Schotterabschnitt der ganzen Reise.</b>"),
 ("14:00","checkin","Check-in Woodall Country House","Woodall Farm, Jan Smuts Avenue, Addo. Tische im Restaurant sind für Hausgäste automatisch reserviert."),
]),
("Mi 21. Okt","7","Addo","Addo Elephant National Park","stand",[
 ("06:45","tipp","Selbstfahrer-Safari im Addo NP","Nur 18–22 Min ab Woodall. Tor öffnet 07:00. Im eigenen Auto mit Klimaanlage – die entspannteste Safariform mit Kindern. <b>Ausweis mitbringen</b>, das ist Pflicht.",165),
 ("","warnung","Woodalls eigene Game Drives: ab 6 Jahren","Die geführten Fahrten von Woodall (R2150 p.P., 07:30 und 14:00) haben <b>Mindestalter 6</b> – ausser als private Safari. Auch die Parkfahrten von Addo selbst sind erst ab 6. Für euch also: selbst fahren."),
 ("13:00","frei","Pause","",90),
 ("16:00","tipp","Addo Main Camp Wasserloch & Underground Hide","Im Eintritt enthalten. Elefanten auf Augenhöhe wenige Meter vor der Nase, Wasserloch flutlichtbeleuchtet."),
]),
("Do 22. Okt","7","Addo","Sundays River Valley","stand",[
 ("09:00","tipp","Daniell Cheetah Project, Kirkwood","45 Min. Predator Tour genau 1 Std, dazu Streichelbereich mit Kaninchen und Meerschweinchen und handaufgezogene Kudus."),
 ("","tipp","Alternativ: Sundays River Kurz-Bootsfahrt","Colchester. 1,5 Std – die kürzeste Bootsoption, Mindestalter 0. Die grosse Cruise mit Sandboarding dauert 2,5 Std."),
 ("16:00","tipp","Addo Wildlife Centre","5 Min. von Woodall, R20 pro Person, 45 Min. Begehbare Voliere, Eulen, Äffchen. Danach Abendessen im Tangelo im selben Haus."),
]),
("Fr 23. Okt","8","Addo → Lalibela","Mark's Camp","fahrt",[
 ("","warnung","Zeitkritisch: Check-in nur 12:00–13:00","Ihr fahrt <b>nicht selbst ins Camp</b>. Das Auto bleibt an der Rezeption an der N2, ein Ranger bringt euch im Safarifahrzeug weiter (ca. 20–30 Min)."),
 ("10:15","fahrt","Woodall → Lalibela Rezeption","68 km · Google 55–60 Min · <b>realistisch 1:15–1:25 h</b> · R335 südwärts → R342 durch den Addo-Korridor → Paterson → N2 ostwärts 27 km. <b>Spätestens 10:30 losfahren.</b>",85),
 ("","warnung","Navi: „Lalibela Game Reserve\" eingeben","Ausdrückliche Warnung der Lodge: auf keinen Fall einer GPS-Empfehlung über Schotterpisten folgen. Die Zufahrt liegt direkt an der N2."),
 ("12:00","checkin","Check-in Mark's Camp","Lunch ca. 14:00. All-Inclusive."),
 ("16:00","tipp","Erste Safari-Fahrt","Kinder ab 2 Jahren fahren mit, in einem eigenen Fahrzeug mit eigenem Ranger. Familien mit ähnlich alten Kindern werden zusammen eingeteilt.",180),
 ("","tipp","Euer Kind fährt mit","Lalibela nimmt Kinder <b>ab 2 Jahren</b> auf die Safari-Fahrten – mit 4 Jahren passt das. Familien mit ähnlich alten Kindern werden zusammen eingeteilt, es gibt ein eigenes Fahrzeug mit eigenem Ranger. Kinderbetreuung während der Mahlzeiten der Erwachsenen und beim Kinderprogramm ist im Preis enthalten."),
]),
("Sa 24. Okt","8","Lalibela","All-Inclusive","stand",[
 ("06:00","tipp","Morgen-Safari","Sonnenaufgang im Oktober ca. 05:50. Warme Decke und Mütze – im offenen Fahrzeug ist es früh kalt.",180),
 ("10:00","tipp","Kinderprogramm „Tiny Trackers\"","Schnitzeljagd, Basteln, Steine bemalen, Tierspuren bestimmen. Dazu zwei Pools, Jungle Gym und Sandkasten. Zwischen 10 und 16 Uhr passiert auf Safari ohnehin nichts."),
 ("13:00","frei","Pause","Das Camp ist diskret eingezäunt.",90),
 ("16:00","tipp","Nachmittags-Safari","",180),
]),
("So 25. Okt","8","Lalibela","All-Inclusive","stand",[
 ("06:00","tipp","Morgen-Safari","",180),
 ("","tipp","Kinder unter 8 essen früher","Eigenes Kindermenü, eigener Bereich. Sagt Wünsche und Allergien beim Lodge-Manager an."),
 ("16:00","tipp","Nachmittags-Safari","",180),
]),
("Mo 26. Okt","8","Lalibela → Flughafen","Abreise Gqeberha","abreise",[
 ("","warnung","Vier Stunden vor Abflug im Camp starten","Transfer Camp → Rezeption im Safarifahrzeug 20–30 Min, dann 96 km bis zum Flughafen, dazu Mietwagenrückgabe."),
 ("11:00","checkout","Check-out Mark's Camp",""),
 ("10:30","fahrt","Transfer + Fahrt zum Flughafen Gqeberha","Transfer Camp → Rezeption 20–30 Min, dann 96 km · Google 1:05–1:15 h · <b>realistisch 1:35–1:50 h</b> · N2 südwestwärts an Nanaga vorbei → M4 → M9 → M11.",110),
 ("","tipp","Letzter Stopp: SANCCOB oder Grass Roof","SANCCOB Pinguin-Rehabilitation, 15 Min. vom Flughafen, Fütterung 09:30. Oder Grass Roof Farm mit gratis Spielplatz direkt neben den Tischen (08:00–16:30) – damit sich die Kinder vor dem Flug austoben."),
 ("","warnung","Sacramento hat montags zu","Falls ihr das Restaurant in Schoenmakerskop eingeplant hattet."),
]),
]
